### ISSUE TITLE
Question about train_discrim_loss

### ISSUE THREAD

**Issue by sapphireh** [ZeroAct/SceneTextRemover-pytorch#3]
I reimplemented this method by the original setting in SCUT-Enstext dataset, but the training discrimination loss did not decrease after 120 epoch and non-text outputs are bad with lots of error pixels.

**Comment by ZeroAct** [comment]
I just followed the equation 7 in the [paper](https://arxiv.org/pdf/2011.09768.pdf).

You can see my discriminator loss [here](https://github.com/ZeroAct/SceneTextRemover-pytorch/blob/788e49aa5a0b8d9004bb641c2538eca5f83e3c31/train.py#L136-L138).

Thank you!
